### ISSUE TITLE
how to get the annotations of coreferent antecedent?

### ISSUE THREAD

**Issue by Jasperty** [bdhingra/coref-gru#1]
i want to modify your model to other dataset, but i donn't know how to get annotations, could you provide your pre-process scripts?

**Comment by bdhingra** [comment]
Hi, you can look at this codalab bundle on how to preprocess some other dataset:

https://worksheets.codalab.org/bundles/0xa32632e302a24e05821fd021055e5f79/

This was used for official WikiHop evaluation. Running ./src/runAll reproduces the whole pipeline.
